### ISSUE TITLE
Unable to install fabric manager 550 via apt get install

### ISSUE THREAD

**Issue by sumanth1989** [NVIDIA/apt-packaging-fabric-manager#3]
sudo apt-get install cuda-drivers-fabricmanager-550
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package cuda-drivers-fabricmanager-550 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'cuda-drivers-fabricmanager-550' has no installation candidate

Also searched for the package

apt search cuda-drivers-fabricmanager
Sorting... Done
Full Text Search... Done
cuda-drivers-fabricmanager/unknown,unknown 550.54.14-1 amd64
  (none)

cuda-drivers-fabricmanager-450/jammy-updates,jammy-security 450.248.02-0ubuntu0.22.04.1 amd64
  Meta-package for FM and Driver

cuda-drivers-fabricmanager-455/unknown 455.45.01-1 amd64
  (none)

cuda-drivers-fabricmanager-460/jammy-updates,jammy-security 510.85.02-0ubuntu0.22.04.1 amd64
  Transitional package for cuda-drivers-fabricmanager-510

cuda-drivers-fabricmanager-465/unknown 465.19.01-1 amd64
  (none)

cuda-drivers-fabricmanager-470/jammy-updates,jammy-security 470.239.06-0ubuntu0.22.04.1 amd64
  Meta-package for FM and Driver

cuda-drivers-fabricmanager-495/unknown 495.29.05-1 amd64
  (none)

cuda-drivers-fabricmanager-510/jammy-updates,jammy-security 515.105.01-0ubuntu0.22.04.1 amd64
  Transitional package for cuda-drivers-fabricmanager-515

cuda-drivers-fabricmanager-515/jammy-updates,jammy-security 525.147.05-0ubuntu0.22.04.1 amd64
  Transitional package for cuda-drivers-fabricmanager-525

cuda-drivers-fabricmanager-520/unknown,unknown 520.61.05-1 amd64
  (none)

cuda-drivers-fabricmanager-525/jammy-updates,jammy-security 525.147.05-0ubuntu0.22.04.1 amd64
  Meta-package for FM and Driver

cuda-drivers-fabricmanager-530/unknown,unknown 530.30.02-1 amd64
  (none)

cuda-drivers-fabricmanager-535/jammy-updates,jammy-security 535.161.07-0ubuntu0.22.04.1 amd64
  Meta-package for FM and Driver

cuda-drivers-fabricmanager-545/unknown,unknown 545.23.08-1 amd64
  (none)

cuda-drivers-fabricmanager-550/unknown,unknown 550.54.14-1 amd64
  (none)

Updated keys and still cant find it
wget https://developer.download.nvidia.com/compute/cuda/repos/debian11/x86_64/cuda-keyring_1.1-1_all.deb
sudo dpkg -i cuda-keyring_1.1-1_all.deb

**Comment by amilonenv** [comment]
hi @sumanth1989 , can you post the output of the following command, please?

`apt-cache policy cuda-drivers-fabricmanager`

**Comment by sumanth1989** [comment]
@amilonenv  - Im not sure what i did wrong or if you guys fixed it but i am able to install it via apt right now. 

apt-cache policy cuda-drivers-fabricmanager
cuda-drivers-fabricmanager:
  Version table:
     550.54.14-1 -1
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  Packages
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages
     545.23.08-1 -1
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  Packages
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages
     545.23.06-1 -1
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  Packages
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages
     535.161.07-1 -1
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  Packages
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages
     535.154.05-1 -1
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  Packages
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages
     535.129.03-1 -1
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  Packages
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages
     535.104.12-1 -1
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  Packages
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages
     535.104.05-1 -1
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  Packages
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages
     535.86.10-1 -1
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  Packages
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages
     535.54.03-1 -1
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  Packages
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages
     530.30.02-1 -1
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  Packages
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages
     525.147.05-1 -1
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  Packages
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages
     525.125.06-1 -1
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  Packages
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages
     525.105.17-1 -1
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  Packages
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages
     525.85.12-1 -1
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  Packages
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages
     525.60.13-1 -1
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  Packages
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages
     520.61.05-1 -1
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  Packages
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages
     515.105.01-1 -1
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  Packages
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages
     515.86.01-1 -1
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  Packages
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages
     515.65.07-1 -1
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  Packages
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages
     515.65.01-1 -1
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  Packages
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages
     515.48.07-1 -1
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  Packages
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages
     515.43.04-1 -1
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  Packages
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages
     510.108.03-1 -1
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages
     510.85.02-1 -1
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages
     510.84-1 -1
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages
     510.73.08-1 -1
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages
     510.47.03-1 -1
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages
     510.39.01-1 -1
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages
     495.29.05-1 -1
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages
     470.239.06-1 -1
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages
     470.223.02-1 -1
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages
     470.199.02-1 -1
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages
     470.182.03-1 -1
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages
     470.161.03-1 -1
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages
     470.141.10-1 -1
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages
     470.141.03-1 -1
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages
     470.129.06-1 -1
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages
     470.103.01-1 -1
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages
     470.82.01-1 -1
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages
     470.57.02-1 -1
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages
     470.42.01-1 -1
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages
     465.19.01-1 -1
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages
     460.106.00-1 -1
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages
     460.91.03-1 -1
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages
     460.73.01-1 -1
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages
     460.32.03-1 -1
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages
     460.27.04-1 -1
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages
     455.45.01-1 -1
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages
     455.32.00-1 -1
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages
     450.248.02-1 -1
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages
     450.236.01-1 -1
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages
     450.216.04-1 -1
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages
     450.203.08-1 -1
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages
     450.203.03-1 -1
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages
     450.191.01-1 -1
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages
     450.172.01-1 -1
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages
     450.156.00-1 -1
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages
     450.142.00-1 -1
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages
     450.119.04-1 -1
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages
     450.119.03-1 -1
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages
     450.102.04-1 -1
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages
     450.80.02-1 -1
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages
     450.51.06-1 -1
        580 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages

**Comment by amilonenv** [comment]
I'm glad to see the problem is solved. Thanks.
